# docker-compose.yml
version: '3'
services:
  tahomahacks-prod:
    build: 
        context: .
        dockerfile: ./Dockerfile.prod
    ports:
        - "3621:3000"
    image: tahomahacks-prod
    user: ${CURRENT_UID}
    working_dir: ${CONTAINER_DEV_HOME}/tahomahacks
    stdin_open: true
    volumes:
      - ${HOST_DEV_HOME}:${CONTAINER_DEV_HOME}
      - ${HOST_DATA_HOME}:${CONTAINER_DATA_HOME}
    tty: true
    command: tail -f /dev/null
    networks:
      main:
        aliases:
          - net-tahomahacks-prod
networks:
  main: